version: '2'
volumes:
    sense-data:
services:
  influxdb:
    restart: always
    build: ./influxdb
    volumes:
      - 'sense-data:/data'
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "80"
    volumes:
      - 'sense-data:/data'
    environment:
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
        - 'GF_SESSION_PROVIDER=memory'
    depends_on:
      - influxdb
  counter:
    restart: always
    build: ./counter
    privileged: true
  wifi-repeater:
   build: .
   privileged: true
   labels:
     io.balena.features.dbus: '1'
  sh_pijuice:
    container_name: sh_pijuice
    build: ./sh_pijuice
    restart: on-failure
    privileged: true
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    volumes:
      - "cgroup:/sys/fs/cgroup"
    labels:
      io.balena.features.supervisor-api: true
      io.balena.features.dbus: true
      io.balena.features.kernel-modules: true

  