version: '2'
volumes:
    sense-data:
services:
  InfluxDB:
    restart: always
    build: ./influxdb
    volumes:
      - 'sense-data:/data'
  Grafana:
    restart: always
    build: ./grafana
    ports:
      - "80"
    volumes:
      - 'sense-data:/data'
    environment:
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
        - 'GF_SESSION_PROVIDER=memory'
    depends_on:
      - influxdb
  Counter:
    restart: always
    build: ./counter
    privileged: true
  WiFi:
   build: .
   privileged: true
   labels:
     io.balena.features.dbus: '1'
  GPS:
    restart: always
    build: ./gps
    privileged: true
  PiJuice:
    build: ./pijuice
    privileged: true
    labels: 
      io.balena.features.balena-api: '1'